### ISSUE TITLE
write etl scripts to hydrate data model for deposits and withdrawals

### ISSUE THREAD

**Issue by amarante-codes** [msquaredsa-ds-dev/user-dash#3]

**Comment by amarante-codes** [comment]
coingecko api 
backfill historicals

**Comment by 0xBlackfish** [comment]
I've tested the historical backfill using Galileo's notebook in the [mainnet-tvl-snapshot repo](https://github.com/Friktion-Labs/mainnet-tvl-snapshots/blob/main/notebooks/Friktion_User_Activity.ipynb). Made slight modifications in order to breakout the source tables separately.

I have also created a prototype data model for the deposits and withdrawals data from the source to the fact level.

Next step is to decompose G's script into individual pieces that can be run on an automated basis.

**Comment by 0xBlackfish** [comment]
@amarante-codes - I modified G's script so that it could be applied generally without the CSV output component. I tested the new backfill function and it worked great for withdrawals. I'll also run it for the rest of the userAction types tomorrow.

Lastly, went ahead and started to add the code necessary for the recurring ETL. Feel free to look through all of this and clean it up / code review.
