### ISSUE TITLE
create mvp data schema for user tables

### ISSUE THREAD

**Issue by amarante-codes** [msquaredsa-ds-dev/user-dash#7]
The user table is gong to be a foundational table that needs to align closely with the deposit and withdraw tables.

Accordingly, we are working to develop an MVP for Friktion core team reaction when we submit the initial formal grant proposal for the user analysis.

**Comment by 0xBlackfish** [comment]
**Thoughts:**
- Instead of deposit_address, could we call it "user_address"? This would be consistent with how I'm naming in both deposit and withdraw tables.
- Need to add an "as_of_date" field (probably daily, but if you think this is too granular we could move it to a higher grain)
- I might suggest adding first_deposit_token and last_deposit_token  as fields
- I feel like we should also have a way to represent user holdings in their entirety (e.g. what Volts they have funds in and how much)
- Longer term, it also probably makes sense to integrate user profitability into the table as well.
- Might consider adding a "days_since_last_deposit" field
- Might also consider adding a "has churned" or "churn_date" / "churn_epoch" field

**Questions**
- In addition to the is_lightning_og_holder field, should we also add a "was_lightning_og_holder" field? This might be redundant, so feel free to disregard if you think so.
- Does AUM Delta refer to the difference between assets held as of the "as _of_date" and the delta number specified in the column?
- Same question as above except for the epoch-related aum fields.
- Should total_deposited and total_withdraw be USD denominated fields?

**Comment by amarante-codes** [comment]
Ok, aligning to user_address.

as_of_date make sense as well, adding.

I like the first and last deposit token as well - great idea - adding as well.

days since last deposit is a good idea, adding. +epochs since last deposit

churn fields are also great ideas - adding all.

the historical view of lightning OGs is likely wise. Adding with a small name revision to ever lightning og holder.

the aum deltas are exactly what you're thinking.

adding the dollar denominations to total_deposited and total_withdrawn

**Comment by 0xBlackfish** [comment]
@amarante-codes - you may also want to consider adding code to "create the `users` schema", and then lines to check whether or not the schema/table already exists. I've added these in friktion_source_tables.py file for reference.

**Comment by amarante-codes** [comment]
@msquaredsa-ds-dev I am pushing two of your comments out to a different issue/feature that we can schedule for future milestone.

These two:

- I feel like we should also have a way to represent user holdings in their entirety (e.g. what Volts they have funds in and how much)
- Longer term, it also probably makes sense to integrate user profitability into the table as well.

**Comment by amarante-codes** [comment]
@msquaredsa-ds-dev also thinking about your discord comments re: the table name. Thinking about changing over to volt_user since so far this project seems exclusively focused on users of, deposits into, and withdrawals from Volts.

thoughts?

**Comment by 0xBlackfish** [comment]
Hmm.....if this is the schema for a rolled up agg user table, I think I bias towards keeping it more general. As the team develops more products, it might be easier to simply add fields such as, `is_volt_user`, `is_entropy_user`, etc. Right now, I agree that this just pertains to volts, but will likely expand in the future.
